# Generated by Django 3.2.10 on 2021-12-26 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品類別')),
            ],
            options={
                'verbose_name': '商品類別',
                'verbose_name_plural': '商品類別',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=3)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.PositiveBigIntegerField()),
                ('quantity', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField()),
            ],
            options={
                'verbose_name': '訂單內容資料',
                'verbose_name_plural': '訂單內容資料',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=255)),
                ('amount', models.IntegerField()),
                ('is_pay', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '訂單資訊',
                'verbose_name_plural': '訂單資訊',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用戶資訊',
                'verbose_name_plural': '用戶資訊',
                'ordering': ('-user_id',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNB_Bot.category')),
            ],
            options={
                'verbose_name': '商品資訊',
                'verbose_name_plural': '商品資訊',
                'ordering': ('-id',),
            },
        ),
    ]
