# Generated by Django 3.2.10 on 2021-12-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNB_Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('-id',), 'verbose_name': '訂單項目資料', 'verbose_name_plural': '訂單項目資料'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-created_time',), 'verbose_name': '訂單資訊', 'verbose_name_plural': '訂單資訊'},
        ),
    ]
